const imageAltText = [
  "card00: one green empty triangle",
  "card01: one green empty square",
  "card02: one green empty circle",
  "card03: one orange empty triangle",
  "card04: one orange empty square",
  "card05: one orange empty circle",
  "card06: one purple empty triangle",
  "card07: one purple empty square",
  "card08: one purple empty circle",
  "card09: two green empty triangles",
  "card10: two green empty squares",
  "card11: two green empty circles",
  "card12: two orange empty triangles",
  "card13: two orange empty squares",
  "card14: two orange empty circles",
  "card15: two purple empty triangles",
  "card16: two purple empty squares",
  "card17: two purple empty circles",
  "card18: three green empty triangles",
  "card19: three green empty squares",
  "card20: three green empty circles",
  "card21: three orange empty triangles",
  "card22: three orange empty squares",
  "card23: three orange empty circles",
  "card24: three purple empty triangles",
  "card25: three purple empty squares",
  "card26: three purple empty circles",
  "card27: one green striped triangle",
  "card28: one green striped square",
  "card29: one green striped circle",
  "card30: one orange striped triangle",
  "card31: one orange striped square",
  "card32: one orange striped circle",
  "card33: one purple striped triangle",
  "card34: one purple striped square",
  "card35: one purple striped circle",
  "card36: two green striped triangles",
  "card37: two green striped squares",
  "card38: two green striped circles",
  "card39: two orange striped triangles",
  "card40: two orange striped squares",
  "card41: two orange striped circles",
  "card42: two purple striped triangles",
  "card43: two purple striped squares",
  "card44: two purple striped circles",
  "card45: three green striped triangles",
  "card46: three green striped squares",
  "card47: three green striped circles",
  "card48: three orange striped triangles",
  "card49: three orange striped squares",
  "card50: three orange striped circles",
  "card51: three purple striped triangles",
  "card52: three purple striped squares",
  "card53: three purple striped circles",
  "card54: one green solid triangle",
  "card55: one green solid square",
  "card56: one green solid circle",
  "card57: one orange solid triangle",
  "card58: one orange solid square",
  "card59: one orange solid circle",
  "card60: one purple solid triangle",
  "card61: one purple solid square",
  "card62: one purple solid circle",
  "card63: two green solid triangles",
  "card64: two green solid squares",
  "card65: two green solid circles",
  "card66: two orange solid triangles",
  "card67: two orange solid squares",
  "card68: two orange solid circles",
  "card69: two purple solid triangles",
  "card70: two purple solid squares",
  "card71: two purple solid circles",
  "card72: three green solid triangles",
  "card73: three green solid squares",
  "card74: three green solid circles",
  "card75: three orange solid triangles",
  "card76: three orange solid squares",
  "card77: three orange solid circles",
  "card78: three purple solid triangles",
  "card79: three purple solid squares",
  "card80: three purple solid circles",
];

export const getAltText = (image: number) => {
  return imageAltText[image];
};

export default () => {
  return [
    require("../images/card00.png"), require("../images/card01.png"), require("../images/card02.png"),
    require("../images/card03.png"), require("../images/card04.png"), require("../images/card05.png"),
    require("../images/card06.png"), require("../images/card07.png"), require("../images/card08.png"),
    require("../images/card09.png"), require("../images/card10.png"), require("../images/card11.png"),
    require("../images/card12.png"), require("../images/card13.png"), require("../images/card14.png"),
    require("../images/card15.png"), require("../images/card16.png"), require("../images/card17.png"),
    require("../images/card18.png"), require("../images/card19.png"), require("../images/card20.png"),
    require("../images/card21.png"), require("../images/card22.png"), require("../images/card23.png"),
    require("../images/card24.png"), require("../images/card25.png"), require("../images/card26.png"),
    require("../images/card27.png"), require("../images/card28.png"), require("../images/card29.png"),
    require("../images/card30.png"), require("../images/card31.png"), require("../images/card32.png"),
    require("../images/card33.png"), require("../images/card34.png"), require("../images/card35.png"),
    require("../images/card36.png"), require("../images/card37.png"), require("../images/card38.png"),
    require("../images/card39.png"), require("../images/card40.png"), require("../images/card41.png"),
    require("../images/card42.png"), require("../images/card43.png"), require("../images/card44.png"),
    require("../images/card45.png"), require("../images/card46.png"), require("../images/card47.png"),
    require("../images/card48.png"), require("../images/card49.png"), require("../images/card50.png"),
    require("../images/card51.png"), require("../images/card52.png"), require("../images/card53.png"),
    require("../images/card54.png"), require("../images/card55.png"), require("../images/card56.png"),
    require("../images/card57.png"), require("../images/card58.png"), require("../images/card59.png"),
    require("../images/card60.png"), require("../images/card61.png"), require("../images/card62.png"),
    require("../images/card63.png"), require("../images/card64.png"), require("../images/card65.png"),
    require("../images/card66.png"), require("../images/card67.png"), require("../images/card68.png"),
    require("../images/card69.png"), require("../images/card70.png"), require("../images/card71.png"),
    require("../images/card72.png"), require("../images/card73.png"), require("../images/card74.png"),
    require("../images/card75.png"), require("../images/card76.png"), require("../images/card77.png"),
    require("../images/card78.png"), require("../images/card79.png"), require("../images/card80.png"),
  ];
};
